### PR TITLE
Integrate ant design

### PR DESCRIPTION
**Pull request by BartDeCaluwe**
This PR will install and configure AntDesign ensuring that it plays nicely together with Tailwind. 
It contains a `theme.js` file that contains shared theme config for NextJS, Tailwind and Storybook.
It also configures Storybook, so it uses the correct fonts and theme colors. 

Some notes:
- I copied the `.editorconfig`, `.prettierrc` and `tsconfig` from the V1 app. This is why there are many formatting changes. 
- The colors found in `theme.js` are not final and based on the figma style guide.
- The fonts are loaded via CDN (as was the case in the V1 of the app). Not sure what the policy is regarding third party libraries and CDNs. 
- Dark mode is supported by using the tailwind `dark:` modifier. AntDesign does have a dark theme, but it's a separate `.less` file and does not support the `prefers-color-scheme` media feature out of the box.

### CODE REVIEW

**Comment by BartDeCaluwe** [comment]
So it seems that there are some CVEs. 
Whats the recommended procedure here, adding the offending packages to `resolutions` or is there a better way?

**Comment by RuvendeGroote** [comment]
it would have been more reviewable if the editorconfig + prettier stuff was in a separate PR so we don't have so much formatting changes mixed with new functionality.

**Comment by RuvendeGroote** [comment]
adding editorconfig and updating prettier could be a single commit (maybe even add the formatting).
already nice commit messages. I am working on a git style guide so we have a set of commit types to pick from. this will also be used in upcoming versioning tools integrations but good that you are already paying attention to it! :)
I would reserve 'fix' for bugs that need to be fixed. bugs you introduce during development and then solve within the same branch should probably be cleaned up by fixing up another commit or something.

**Comment by RuvendeGroote** [comment]
Can you add "It contains a theme.js file that contains shared theme config for NextJS, Tailwind and Storybook.
It also configures Storybook, so it uses the correct fonts and theme colors."  to the readme? (but worded more appropriately for a readme)
+
"Dark mode is supported by using the tailwind dark: modifier. AntDesign does have a dark theme, but it's a separate .less file and does not support the prefers-color-scheme media feature out of the box."

And maybe just explain our storybook setup in the readme because it's not yet mentioned there it seems

**Comment by RuvendeGroote** [comment]
> So it seems that there are some CVEs. Whats the recommended procedure here, adding the offending packages to `resolutions` or is there a better way?

we should have a discussion about this as a team. in the previous app we let the dependabot alerts pile up but this time we need to keep on top of things (also work out a dependency update/maintenance strategy)

**Comment by BartDeCaluwe** [comment]
> I would reserve 'fix' for bugs that need to be fixed. bugs you introduce during development and then solve within the same branch should probably be cleaned up by fixing up another commit or something.

Agreed, using `fix` already didn't feel right for me. Especially if we're ever going to generate changelogs based on our commits. 
What do you mean with "fixing up another commit" exactly?

**Comment by BartDeCaluwe** [comment]
> > So it seems that there are some CVEs. Whats the recommended procedure here, adding the offending packages to `resolutions` or is there a better way?
> 
> we should have a discussion about this as a team. in the previous app we let the dependabot alerts pile up but this time we need to keep on top of things (also work out an dependency update/maintenance strategy)

Well, normally I'd just run `npm audit fix` but it seems that `yarn` doesn't have the `fix` option.
I've looked into it and there are a couple of options:
- Use `resolutions` in `package.json` and add the fixed versions of the affected packages so that dependencies that rely on the affected package use that list to resolve their deps
- Use `yarn upgrade-interactive` and update the affected packages manually
- Use `yarn-audit-fix` which is an npm package that emulates `npm audit fix`

There are probably other ways we can deal with this. We should definitely have a discussion about this, so we can agree on a way of working.

Edit: Some CVEs related to storybook cannot be fixed yet. See [this issue](https://github.com/storybookjs/storybook/issues/14603). Though it seems they are working on it.

**Comment by RuvendeGroote** [comment]
> > I would reserve 'fix' for bugs that need to be fixed. bugs you introduce during development and then solve within the same branch should probably be cleaned up by fixing up another commit or something.
> 
> Agreed, using `fix` already didn't feel right for me. Especially if we're ever going to generate changelogs based on our commits. What do you mean with "fixing up another commit" exactly?

I meant stuff like amending or editing commits

**Review by RuvendeGroote — APPROVED** [review]

**Review by BouweCeunen — APPROVED** [review]

**Pull request merged**
